---
title: "Checking Fibroblast markers"
author: "Sophie.Alice"
date: "2026-07-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---



# Setup

```{r, message=FALSE, warning = FALSE}
rm(list=ls())
gc()

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(hdf5r)
library(scCustomize)
library(patchwork)
library(cowplot)
library(ggrepel)
library(workflowr)
library(scDblFinder)
library(clustree)
library(harmony)
library(speckle)
library(MAST)
library(tibble)
library(EnhancedVolcano)
library(UpSetR)
library(grid)
library(ggvenn)

library(ggarchery)
library(ggtangle)
library(clusterProfiler)
library(org.Hs.eg.db)
library(GO.db)
library(DOSE)
library(fgsea)
library(forcats)
library(SCpubr)
library(assertthat)
library(UCell)
library(DT)

library(ggforce) 
library(enrichplot)
library(ggrain)
```


# Get the Data

```{r, warning = FALSE}
path <- "/Users/sophiewagner/Desktop/USZ 25:26/Gabi_Project_Setup/Laila_MT_Project/Laila_MT_Project/RDS_Files/Post_Annotation.rds"
Data <- read_rds(path)
Data


custom_palette <- colorRampPalette(c("#005EA8", "#6DB335", "#FFD966", "#EDAAD2", "#9F1C67"))
gradient_colors3 <- custom_palette(6)
gradient_colors4 <- custom_palette(4)
gradient_colors3 <- custom_palette(3)

```



# Functions

```{r, warning = FALSE}


Volcano_Plots <- function(Data, Title, Subtitle, pCutoff = 0.05, FCcutoff = 0.5) {
  
  # Clean extreme values
  df <- Data
  df <- df[is.finite(df$avg_log2FC) & is.finite(df$p_val_adj), ]
  
  # dynamic axis limits
  xmax <- max(df$avg_log2FC, na.rm = TRUE)
  xmin <- min(df$avg_log2FC, na.rm = TRUE)
  ymax <- max(-log10(df$p_val_adj), na.rm = TRUE)
  
  # Add padding
  xpad <- (xmax - xmin) * 0.1
  ypad <- ymax * 0.1
  
  combined_subtitle <- paste0(Subtitle, " ● Thresholds: FDR < ", pCutoff, ", |Log2FC| > ", FCcutoff)
  
  EV <- EnhancedVolcano(
    df,
    lab = df$gene,
    x = 'avg_log2FC',
    y = 'p_val_adj',
    xlab = 'log2 Foldchange',
    ylab = "-log10 FDR",
    legendLabels = c('NS','log2FC','FDR','FDR & log2FC'),
    col = c("darkgrey", "#005EA8", "#FFD966", "#9F1C67"),
    title = Title,
    subtitle = combined_subtitle,   
    xlim = c(xmin - xpad, xmax + xpad),
    ylim = c(0, ymax + ypad),
    pCutoff = pCutoff,              
    FCcutoff = FCcutoff,            

    cutoffLineType = 'dashed',      
    cutoffLineCol = 'black',        
    cutoffLineWidth = 0.6,
    labSize = 3.0,
    drawConnectors = TRUE,
    widthConnectors = 0.5
  )
  
  return(EV)
}

##################################### Tables

create_table <- function(df) {
  DT::datatable(
    df,
    extensions = 'Buttons', 
    options = list(
      dom = 'Blfrtip',                       
      buttons = c('copy', 'csv', 'excel', 'pdf'),
      pageLength = 10,                      
      lengthMenu = c(10, 25, 50, 100),
      autoWidth = TRUE,
      columnDefs = list(list(
        targets = '_all',
        className = 'dt-nowrap'
      ))
    ),
    filter = 'top',                         
    class = 'cell-border stripe hover nowrap'       
  )
}

#################################################### Raincloud Plots

raincloud.plots <- function(gene_list, 
                                   plot_title, 
                                   plot_subtitle, 
                                   seurat_obj = Data, 
                                   colors = gradient_colors4) {

  
  valid_genes <- intersect(gene_list, rownames(seurat_obj))
  expression_matrix <- FetchData(seurat_obj, vars = c(valid_genes, "ident")) 

  
  rain_data <- expression_matrix %>%
    tibble::rownames_to_column("Cell_ID") %>%
    tidyr::pivot_longer(
      cols = all_of(valid_genes), 
      names_to = "Gene", 
      values_to = "Expression"
    ) %>%
    dplyr::rename(Condition = ident)
  

  raincloud_plot <- ggplot(rain_data, aes(x = Condition, y = Expression, fill = Condition, color = Condition)) +
    geom_rain(
      alpha = 0.6,
      violin.args = list(color = NA),          
      boxplot.args = list(outlier.shape = NA), 
      point.args = list(
        size = 0.4,                            
        alpha = 0.4                            
      ),
    group = 1
    ) +
    
    facet_wrap(~Gene, scales = "free_y", ncol = 3) +
    
    scale_fill_manual(values = colors) +
    scale_color_manual(values = colors) +
    
    theme_bw() +
    labs(
      title    = plot_title,
      subtitle = plot_subtitle,
      x        = "Experimental Conditions",
      y        = "Normalized Expression Level"
    ) +
    
    theme(
      plot.title.position = "plot",
      plot.title    = element_text(face = "bold", size = 12, hjust = 0),
      plot.subtitle = element_text(face = "italic", size = 10, hjust = 0),
      axis.text.x   = element_text(angle = 45, hjust = 1, face = "bold", color = "black"),
      axis.text.y   = element_text(face = "bold", color = "black"),
      axis.title.x  = element_text(face = "bold"),
      axis.title.y  = element_text(face = "bold"),
      strip.text    = element_text(face = "bold", size = 10), 
      legend.position = "none"
    )
  
  return(raincloud_plot)
}

###################################### Feature Plots

plot_features <- function(seurat_obj, features, title = NULL, subtitle = NULL, num_columns = 3) {
  p <- FeaturePlot_scCustom(seurat_obj, features = features, num_columns = num_columns)

  p <- p + patchwork::plot_annotation(
    title = title,
    subtitle = subtitle,
    theme = ggplot2::theme(
      plot.title.position = "plot",
      plot.title    = ggplot2::element_text(face = "bold", size = 12, hjust = 0),
      plot.subtitle = ggplot2::element_text(face = "italic", size = 10, hjust = 0)
    )
  )
  
  return(p)
}

```


# Subsetting the fibroblasts

```{r, warning = FALSE, fig.width=8, fig.height=12}

Fibroblasts <- subset(Data, cell_type == "Cardiac Fibroblasts")
Idents(Fibroblasts) <- "orig.ident" 

```

# Biomarkers from Gino DCM subclustering analysis

```{r, warning = FALSE, fig.width=8, fig.height=12}

gino.markers <- c("ACSM3", "PDZRN4", "FGF14", "KAZN", "NFATC2", 
"POSTN", "ACTA2", "FAP", "VIM", "COL1A1", "FN1", "SHISA6", "CNTNAP2", "NFATC2")
                                              
plot_features(Fibroblasts, features = gino.markers, 
              title = "Unmodified Fibroblast Subset", subtitle = "Gino Markers")

```


# Biomarkers obtained through small talk with chatgpt (Maks and Magda):

```{r, warning = FALSE, fig.width=8, fig.height=12}


chat.markers <- c("COL1A1", "TNC", "COL3A1", "FN1", # fibroblasty produkujące ECM
                    "FOS", "JUN", "EGR1", "HSPA1A", # fibroblasty stresowe
                          "COL15A1", "CD34", "PI16") # fibroblasty związane zremodellingiem naczyń

chat.markers2 <- c("ACTA2", "TAGLN", "MYH11", "CCN2", # miofibroblasty
                    "POSTN", "FAP", "CTHRC1", "COMP", # fibroblasty związane z włóknieniem
                        "DCN", "LUM", "DPT", "SHISA6") # fibroblasty rezydentne
                                              
plot_features(Fibroblasts, features = chat.markers, 
              title = "Unmodified Fibroblast Subset", subtitle = "Chat Markers")

plot_features(Fibroblasts, features = chat.markers2, 
              title = "Unmodified Fibroblast Subset", subtitle = "Chat Markers")


```

# Biomarkers from Reichart paper:

```{r, warning = FALSE, fig.width=8, fig.height=7}
# lipogenic markers
Reichard.lipo <- c("APOD", "APOE", "CST3")
plot_features(Fibroblasts, features = Reichard.lipo, 
              title = "Unmodified Fibroblast Subset", subtitle = "Reichart lipogenic Markers")

# Cytoskeletal markers 
Reichard.cytosk <- c("DAAM1", "GPC6")
plot_features(Fibroblasts, features = Reichard.cytosk, 
              title = "Unmodified Fibroblast Subset", subtitle = "Reichart Cytoskeletal Markers")

# biomarkers_inflammatory
Reichard.inflm <- c("CCL2", "IL6ST", "OSMR")
plot_features(Fibroblasts, features = Reichard.inflm, 
              title = "Unmodified Fibroblast Subset", subtitle = "Reichart inflammatory Markers")

# biomarkers_fibrosis
Reichard.fibrosis <- c("TGFB2", "PCOLCE2", "COL4A1", "COL4A2")
plot_features(Fibroblasts, features = Reichard.fibrosis, 
              title = "Unmodified Fibroblast Subset", subtitle = "Reichart fibrosis Markers")


```


# Biomarkers from Maatz publication:

```{r, warning = FALSE, fig.width=8, fig.height=7}

maatz.markers <- c("MGP", "APOD", "CFD", "GSN", "SERPINF1")

plot_features(Fibroblasts, features = maatz.markers, 
              title = "Unmodified Fibroblast Subset", subtitle = "Maatz Markers")

```

# Biomarkers Gabi

```{r, warning = FALSE, fig.width=8, fig.height=12}

gabi.markers <- c("COMP", "CLIP1", "CHAD", "THBS4",
                  "PDPN", "DYSF", "POSTN",
                  "FAP", "ACTA2", "MXRA5",
                  "FOSL2")

plot_features(Fibroblasts, features = gabi.markers, 
              title = "Unmodified Fibroblast Subset", subtitle = "Gabi Markers")

```




```{r, warning = FALSE, fig.width=8, fig.height=7}



```


```{r, warning = FALSE, fig.width=8, fig.height=7}



```

