---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Project MT

## Data Processing & Global Overview

* [1. Cellbender vs. Raw Data QC Comparison](Checking_Cellbender.html)
* [2. Quality Control (QC)](QC.html)
* [3. Clustering and Annotation](Dim_Reduction.html)
* [3.1 Cell scores](Checking_celscores.html)
* [4. Celltype Proportions](Proportions.html)


## Cardiomyocyte Subset

* **5. Cardiomyocyte Subset**
    * [5. CM Subtypes](CM_Subtypes.html)

## Macrophages DGEA

* **6. Macrophages Subset**
    * [6.1 Differential Gene Expression (DGEA)](Macrophage_subset_DGEA.html)
    * [6.2 DGEA - Lenient Thresholds](Macrophage_subset_DGEA_Lenient.html)

## Fibroblast DGEA

* **7.0 Global Comparisons**
    * [Overview & DEG Overlap](Fibroblasts_DEG_Overlap.html)
    * [All Fibroblast Comparisons Dashboard](Fibroblast_Comparisons.html)

* **7.1 Standard Thresholds (DGEA)**
    * [Overview Dashboard](DGEA.html)
    * [7.1.1 Baseline TGF-$\beta$ Response](Fibro_Baseline_TGF_Response.html)
    * [7.2.2 Modulated TGF-$\beta$ Response](Fibro_Modulated_TGF_Response_Lenient.html)
    * [7.1.3 Baseline Macrophage Response](Fibro_Baseline_Mac_Response.html)
    * [7.1.4 Stimulated Macrophage Response](Fibro_Stim_Mac_Response.html)

* **7.2 Lenient Thresholds (DGEA)**
    * [Overview Dashboard](DGEA_Lenient.html)
    * [7.2.1 Baseline TGF-$\beta$ Response](Fibro_Baseline_TGF_Response_Lenient.html)
    * [7.2.2 Modulated TGF-$\beta$ Response](Fibro_Modulated_TGF_Response_Lenient.html)
    * [7.2.3 Baseline Macrophage Response](Fibro_Baseline_Mac_Response_Lenient.html)
    * [7.2.4 Stimulated Macrophage Response](Fibro_Stim_Mac_Response_Lenient.html)


* **7.3 Subclusters of Fibroblasts**
    * [Unmodified - Fibroblast Marker](fib_markers.html)
    * [Modified - Fibroblast Marker](Subclusters_Fib.html)
    
## Fibroblast DGEA Method comparison

* **X.1 DGEA - Comparison of 3 Methods**
    * [X.1.1 NC vs. Macrophages](Method1_Baseline_Mac_Response_Lenient.html)
    * [X.1.2 TGF-$\beta$ vs. Macrophages + TGF-$\beta$](Methods_Stim_Mac_Response_Lenient.html)
    * [X.1.3 NC vs. TGF-$\beta$](Methods_Baseline_TGF_Response_Lenient.html)

## Cardiomyocytes DGEA

* **8.1 Standard Thresholds (DGEA)**
    * [Overview Dashboard](CM_DGEA.html)
    * [8.1.1 Baseline TGF-$\beta$ Response](CM_Baseline_TGF_Response.html)
    * [8.1.2 Modulated TGF-$\beta$ Response](CM_Modulated_TGF_Response.html)
    * [8.1.3 Baseline Macrophage Response](CM_Baseline_Mac_Response.html)
    * [8.1.4 Stimulated Macrophage Response](CM_Stim_Mac_Response.html)

* **8.2 Lenient Thresholds (DGEA)**
    * [Overview Dashboard](CM_DGEA_Lenient.html)
    * [8.2.1 Baseline TGF-$\beta$ Response](CM_Baseline_TGF_Response_Lenient.html)
    * [8.2.2 Modulated TGF-$\beta$ Response](CM_Modulated_TGF_Response_Lenient.html)
    * [8.2.3 Baseline Macrophage Response](CM_Baseline_Mac_Response_Lenient.html)
    * [8.2.4 Stimulated Macrophage Response](CM_Stim_Mac_Response_Lenient.html)

